name: Debug Compile
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile test
        run: |
          clang++ -c -arch arm64 -isysroot $(xcrun --sdk iphoneos --show-sdk-path) fluck.mm
